name: Mirror and run GitLab CI

on:
  [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirrror + trigger CI
      uses: lutengda/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.teleport.cnosdb.com/root/cnosdb"
      env:
        FOLLOW_TAGS: "false"
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "192.168.0.11:8280"
        GITLAB_USERNAME: "root"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "9"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
